name: Auto Build Docker Image

on:
  workflow_dispatch:
  release:
    - '*'

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set Release Tag
        run: |
          export TAG=$(cat ReleaseTag | head -n1)
          echo "TAG=$TAG" >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        if: success() && env.TAG != ''

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        if: success() && env.TAG != ''

      - name: Login to DockerHub
        uses: docker/login-action@v1
        if: success() && env.TAG != ''
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        if: success() && env.TAG != ''
        with:
          context: .
          push: true
          platforms: linux/amd64
          tags: |
            zhangsean/bili-helper:latest,
            zhangsean/bili-helper:${{ env.TAG }}
